# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15a2a22a6547a4b141d1946b8b3e3f18f30f0948ec9cb562f8d8588034bfb80984fd5878d5d73b8471835af463a807dd0be61d6a76e72dae29c622739a7bed2f

test:
  secret_key_base: 662eed06ea72a8b7467c4ae81d225d5e56c32a1b691691aa1f609f0e95740ed6ce907d81f06bcabfb80647d79c8bd9b1748ed91b1175d01b1e318dede473b9e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
